"""
Top 15 gesetzliche Krankenkassen in Deutschland (Account-Liste nach Mitgliederzahl).
"""

KASSEN = [
    {
        "name": "Techniker Krankenkasse",
        "short": "TK",
        "domain": "tk.de",
        "url": "https://www.tk.de",
        "linkedin_search": "Techniker Krankenkasse",
        "linkedin_url": "https://www.linkedin.com/company/techniker-krankenkasse/",
        "linkedin_company_id": "41317",
    },
    {
        "name": "BARMER",
        "short": "BARMER",
        "domain": "barmer.de",
        "url": "https://www.barmer.de",
        "linkedin_search": "BARMER Krankenkasse",
        "linkedin_url": "https://www.linkedin.com/company/barmer/",
        "linkedin_company_id": "18012268",
    },
    {
        "name": "DAK-Gesundheit",
        "short": "DAK",
        "domain": "dak.de",
        "url": "https://www.dak.de",
        "linkedin_search": "DAK-Gesundheit",
        "linkedin_url": "https://www.linkedin.com/company/dak-gesundheit/",
        "linkedin_company_id": "42928985",
    },
    {
        "name": "IKK classic",
        "short": "IKK classic",
        "domain": "ikk-classic.de",
        "url": "https://www.ikk-classic.de",
        "linkedin_search": "IKK classic",
        "linkedin_url": "https://www.linkedin.com/company/ikk-classic/",
        "linkedin_company_id": "1412986",
    },
    {
        "name": "Kaufmännische Krankenkasse (KKH)",
        "short": "KKH",
        "domain": "kkh.de",
        "url": "https://www.kkh.de",
        "linkedin_search": "KKH Kaufmännische Krankenkasse",
        "linkedin_url": "https://www.linkedin.com/company/kkh-kaufmannische-krankenkasse/",
        "linkedin_company_id": "39196",
    },
    {
        "name": "Siemens-Betriebskrankenkasse (SBK)",
        "short": "SBK",
        "domain": "sbk.org",
        "url": "https://www.sbk.org",
        "linkedin_search": "SBK Siemens-Betriebskrankenkasse",
        "linkedin_url": "https://www.linkedin.com/company/sbk-siemens-betriebskrankenkasse/",
    },
    {
        "name": "hkk (Handelskrankenkasse)",
        "short": "hkk",
        "domain": "hkk.de",
        "url": "https://www.hkk.de",
        "linkedin_search": "hkk Handelskrankenkasse",
        "linkedin_url": "https://www.linkedin.com/company/hkk/",
        "linkedin_company_id": "10699871",
    },
    {
        "name": "BKK firmus",
        "short": "BKK firmus",
        "domain": "bkk-firmus.de",
        "url": "https://www.bkk-firmus.de",
        "linkedin_search": "BKK firmus",
        "linkedin_url": "https://www.linkedin.com/company/bkk-firmus/",
    },
    {
        "name": "Mobil Krankenkasse",
        "short": "Mobil KK",
        "domain": "mobil-krankenkasse.de",
        "url": "https://www.mobil-krankenkasse.de",
        "linkedin_search": "Mobil Krankenkasse",
        "linkedin_url": "https://www.linkedin.com/company/mobil-krankenkasse/",
    },
    {
        "name": "Audi BKK",
        "short": "Audi BKK",
        "domain": "audibkk.de",
        "url": "https://audibkk.de",
        "linkedin_search": "Audi BKK",
        "linkedin_url": "https://www.linkedin.com/company/audi-bkk/",
    },
    {
        "name": "VIACTIV Krankenkasse",
        "short": "VIACTIV",
        "domain": "viactiv.de",
        "url": "https://www.viactiv.de",
        "linkedin_search": "VIACTIV Krankenkasse",
        "linkedin_url": "https://www.linkedin.com/company/viactiv-krankenkasse/",
        "linkedin_company_id": "12414104",
    },
    {
        "name": "IKK Südwest",
        "short": "IKK Südwest",
        "domain": "ikk-suedwest.de",
        "url": "https://www.ikk-suedwest.de",
        "linkedin_search": "IKK Südwest",
        "linkedin_url": "https://www.linkedin.com/company/ikk-sudwest/",
    },
    {
        "name": "HEK – Hanseatische Krankenkasse",
        "short": "HEK",
        "domain": "hek.de",
        "url": "https://www.hek.de",
        "linkedin_search": "HEK Hanseatische Krankenkasse",
        "linkedin_url": "https://www.linkedin.com/company/hek-hanseatische-krankenkasse/",
        "linkedin_company_id": "36667598",
    },
    {
        "name": "Pronova BKK",
        "short": "Pronova BKK",
        "domain": "pronovabkk.de",
        "url": "https://www.pronovabkk.de",
        "linkedin_search": "Pronova BKK",
        "linkedin_url": "https://www.linkedin.com/company/pronovabkk/",
    },
    {
        "name": "BAHN-BKK",
        "short": "BAHN-BKK",
        "domain": "bahn-bkk.de",
        "url": "https://www.bahn-bkk.de",
        "linkedin_search": "BAHN-BKK",
        "linkedin_url": "https://www.linkedin.com/company/bahn-bkk/",
    },
]

# GKV-IT-Dienstleister: werden nur im LinkedIn-Radar beobachtet,
# nicht im Web-Research-Batch oder TED-Abruf.
BEOBACHTETE_ORGS = [
    {
        "name": "BITMARCK Unternehmensgruppe",
        "short": "BITMARCK",
        "domain": "bitmarck.de",
        "url": "https://www.bitmarck.de",
        "linkedin_search": "BITMARCK",
        "linkedin_url": "https://www.linkedin.com/company/bitmarck/",
        "linkedin_company_id": "955964",
    },
    {
        "name": "ITSC GmbH",
        "short": "ITSC",
        "domain": "itsc.de",
        "url": "https://www.itsc.de",
        "linkedin_search": "ITSC GmbH",
        "linkedin_url": "https://www.linkedin.com/company/itsc-gmbh/",
        "linkedin_company_id": "8195481",
    },
    {
        "name": "gematik GmbH",
        "short": "gematik",
        "domain": "gematik.de",
        "url": "https://www.gematik.de",
        "linkedin_search": "gematik",
        "linkedin_url": "https://www.linkedin.com/company/gematik/",
        "linkedin_company_id": "125822",
    },
    {
        "name": "adesso SE",
        "short": "adesso",
        "domain": "adesso.de",
        "url": "https://www.adesso.de",
        "linkedin_search": "adesso SE",
        "linkedin_url": "https://www.linkedin.com/company/adesso-se/",
    },
    {
        "name": "arvato Systems",
        "short": "arvato",
        "domain": "arvato-systems.de",
        "url": "https://www.arvato-systems.de",
        "linkedin_search": "arvato Systems",
        "linkedin_url": "https://www.linkedin.com/company/arvato-systems/",
    },
    {
        "name": "INIT Group",
        "short": "INIT",
        "domain": "init.de",
        "url": "https://www.init.de",
        "linkedin_search": "INIT Group",
        "linkedin_url": "https://www.linkedin.com/company/initgroup/",
    },
    {
        "name": "HBSN AG",
        "short": "HBSN",
        "domain": "hbsn.de",
        "url": "https://www.hbsn.de",
        "linkedin_search": "HBSN AG",
        "linkedin_url": "https://www.linkedin.com/company/hbsn-ag/",
    },
    {
        "name": "msg systems ag",
        "short": "msg",
        "domain": "msg.group",
        "url": "https://www.msg.group",
        "linkedin_search": "msg systems ag",
        "linkedin_url": "https://www.linkedin.com/company/msggroup/",
    },
    {
        "name": "iCraft GmbH",
        "short": "iCraft",
        "domain": "icraft.de",
        "url": "https://www.icraft.de",
        "linkedin_search": "iCraft GmbH",
        "linkedin_url": "https://www.linkedin.com/company/icraft-gmbh/",
    },
    {
        "name": "d.velop AG",
        "short": "d.velop",
        "domain": "d-velop.de",
        "url": "https://www.d-velop.de",
        "linkedin_search": "d.velop AG",
        "linkedin_url": "https://www.linkedin.com/company/d-velop/",
    },
    {
        "name": "atacama Software GmbH",
        "short": "atacama",
        "domain": "atacama.de",
        "url": "https://www.atacama.de",
        "linkedin_search": "atacama Software",
        "linkedin_url": "https://www.linkedin.com/company/atacama-software-gmbh/",
    },
]
